---
- hosts: all
  become: true
  pre_tasks:

  - name: Updating Repository Index of CentOS
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Updating Repository Index of Ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  roles:
    - Ubuntu
    - CentOS
