---

- hosts: all
  become: true
  pre_tasks:

  - name: Updating Repository Index of CentOS
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Updating Repository Index of Ubuntu
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu
  become: true
  roles:
   - Ubuntu

- hosts: Ubuntu2
  become: true
  roles:
   - Ubuntu2

- hosts: CentOS
  become: true
  roles:
   - CentOS
